AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
    DuckbillGroupRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: "DuckbillGroup-CFT"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action: "sts:AssumeRole"
                    Principal:
                        AWS: "753095100886"
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
